sec 9 Stock Tracker Social Media/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
end

sec 9 Stock Tracker Social Media/app/models/stock.rb
class Stock < ApplicationRecord

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.sandbox_api_key,
      endpoint: 'https://sandbox.iexapis.com/v1')

      begin
      new(ticker: ticker_symbol,name:client.company(ticker_symbol).company_name,last_price: client.price(ticker_symbol))
      rescue => exception
        return nil
      end
  end
end

sec 9 Stock Tracker Social Media/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

sec 9 Stock Tracker Social Media/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

sec 9 Stock Tracker Social Media/app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: 'users/result' }
        end
      end    
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: 'users/result' }
      end
    end
  end

  # def search
  #   if params[:stock].present?
  #     @stock = Stock.new_lookup(params[:stock])
  #     if @stock
  #       render 'users/my_portfolio'
  #     else
  #       flash[:alert] = "Please enter a valid symbol to search"
  #       redirect_to my_portfolio_path
  #     end    
  #   else
  #     flash[:alert] = "Please enter a symbol to search"
  #     redirect_to my_portfolio_path
  #   end
  # end
end

sec 9 Stock Tracker Social Media/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

sec 9 Stock Tracker Social Media/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index;end
end

sec 9 Stock Tracker Social Media/app/helpers/users_helper.rb
module UsersHelper
end

sec 9 Stock Tracker Social Media/app/views/layouts/_message.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

sec 9 Stock Tracker Social Media/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
  </div>
</nav>

sec 9 Stock Tracker Social Media/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sec 9 Stock Tracker Social Media</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

<%= render 'layouts/navigation' %>
<div class="container">
<%= render 'layouts/message' %>
    <%= yield %>
  </div>
  </body>
</html>

sec 9 Stock Tracker Social Media/app/views/users/_result.html.erb
<% if @stock %>
<div class="card card-header mt-3 results-block">
<strong>Symbol: </strong><%= @stock.ticker%>
<strong>Name: </strong><%= @stock.name%>
<strong>Price: </strong><%= @stock.last_price%>
</div>
<% end %>

sec 9 Stock Tracker Social Media/app/views/users/_result.js.erb
document.querySelector(
  "#results"
).innerHTML = `<%= escape_javascript(render 'users/result.html') %>`;

sec 9 Stock Tracker Social Media/app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='search-area'>
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">

</div>